Ncnews 10
majidfer/BE-NC-News-Feri- pull request #9
Opened 2022-05-19 11:13 UTC by ffm-id

Completed ncnews #10 with corresponding tests

2022-05-19 11:46 UTC, popatre requested changes
Just a few things to change

2022-05-19 11:46 UTC, popatre commented on __tests__/app.test.js
> +            body: "This is a new comment for article_id 1",
What about the other keys? It should have the all i.e. votes, created_at etc

2022-05-19 11:46 UTC, popatre commented on __tests__/app.test.js
> +  test("400: responds with a bad request message when passed invalid username", () => {
404 -username not found.

2022-05-19 11:46 UTC, popatre commented on __tests__/app.test.js
> +  test("400: responds with a not found message when article is not in the database", () => {
this is a valid input for article_id, its just not found. 

404 - article not found

2022-05-19 11:46 UTC, popatre commented on __tests__/app.test.js
> +      .then(({ body }) => {
- [ ] TEST -  400 missing required field on the post body

2022-05-19 16:01 UTC, Rosem10 commented on __tests__/app.test.js
> +      .expect(404)
This still says 400 in the test description

2022-05-19 16:01 UTC, Rosem10 commented on __tests__/app.test.js
> +        expect(body.msg).toBe("Request parameter not found");
I think this should actually be bad request - since our username has to be a string in our database.

2022-05-20 08:32 UTC, popatre approved these changes
Just change that test desc to 404

2022-05-20 08:32 UTC, popatre commented on __tests__/app.test.js
>    test("400: responds with a bad request message when passed invalid username type", () => {
It looks like it till says 400 as Rose said

2022-05-20 08:52 UTC, merged